sudo: required

before_install:
- sudo apt-get install zip
- sudo apt install ccache
- git clone --recursive https://github.com/varunhardgamer/TheRagingBeast_Minimal_A6000 -b master ~/trb
- git clone https://github.com/varunhardgamer/SaberMod_GCC_4.8.2_arm-eabi ~/trb/tc
- git clone https://github.com/varunhardgamer/LazyFlasher ~/trb/lf
script:
- cd ~/trb
- export ARCH=arm
- export CROSS_COMPILE=~/trb/tc/bin/arm-eabi-
- export KBUILD_BUILD_USER="VarunVaishnav"
- export KBUILD_BUILD_HOST="OptimusPrime"
- make lineageos_a6000_defconfig
- make -j128
- cp ~/trb/arch/arm/boot/zImage ~/trb/lf
- cd ~/trb/lf
- zip TheRagingBeast_a6000-CIBuild.zip ~/trb/lf*
- curl --upload-file ./TheRagingBeast_a6000-CIBuild.zip https://transfer.sh/TheRagingBeast_a6000-CIBuild.zip
- echo All Done ;_;
